movieproject/movieapp/urls.py
# from django.urls import path
# from . import views

# urlpatterns = [
#     path('',views.index,name='index')   
# ]


# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Detail View part1
# from django.urls import path
# from . import views

# urlpatterns = [
#     path('',views.index,name='index'),
#     path('movie/<int:movie_id>/',views.detail,name='detail')
# ]


# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Name space in django
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/' ,views.add_movie,name='add_movie'),
    # Update part2
    path('update/<int:id>/',views.update,name='update'),
    #Delete
    path('delete/<int:id>/',views.delete,name='delete')]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include    #,include

from movieproject import settings
from   django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))   #
]

# Load static files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name
    

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields =['name','desc','year','img']

movieproject/movieapp/views.py
# from django.http import HttpResponse
# from django.shortcuts import render
# from . models import Movie

# # Create your views here.
# def index(request):
#     movie=Movie.objects.all()
#     context={
#         'movie_list':movie
#     }
#     return render(request,'index.html',context)

# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Detail View part1

# from django.http import HttpResponse
# from django.shortcuts import render
# from . models import Movie

# # Create your views here.
# def index(request):
#     movie=Movie.objects.all()
#     context={
#         'movie_list':movie
#     }
#     return render(request,'index.html',context)
# def detail(request,movie_id):
#     return HttpResponse("this is movie no %s" % movie_id)


# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Detail View part3

from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from . forms import MovieForm   #Update Part1#

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    return HttpResponse("this is movie no %s" % movie_id)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
#add data to DB#
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,"add.html")

#Update Part1#
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')  #home page lott return varan
    return render(request,'edit.html',{'form':form,'movie':movie})

#delete#
def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data"> 
                    {% comment %} enctype = img file DB manasilavan {% endcomment %}
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter your movie name">
    <input type="text" name="desc" placeholder="Enter your movie description">
    <input type="text" name="year" placeholder="Enter your movie year">
    <input type="file" name="img">
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
   {% comment %} //Navbar// {% endcomment %}
   <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">
         Online movie store
      </a>
   </nav>
   {% block body %}
   {% endblock %}
</body>
</html> 

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this Movie?
    <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}  {% comment %} //ee page base.html lekk varan. or base page kodtha yalla styles um ee page varan  {% endcomment %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="400" height="650">
        </div>
            <div class="col-md-6">
                <h3><b>{{movie.name}}</b></h3>
                <h4><i>{{movie.desc}}</i></h4>
                <h6>{{movie.year}}</h4>
                <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
                <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
            </div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
    {% for i in movie_list %}
    <div class="col-md-3">
        {% comment %} #Bootstrap {% endcomment %}
        <div class="card">
            <img class="card-img-top" src="{{i.img.url}}" alt="" width="500px" height="350px">
            <div class="card-body">
              <h5 class="card-title">{{i.name}}</h5>
              <p class="card-text">{{i.desc}}</p>
              <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

movieproject/templates/index_old.html
{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
</head>
<body> {% endcomment %}
   {% comment %}//{{movie_list}}//  {% endcomment %}
   {% comment %} {% for i in movie_list %}
   {{i.id}}-->{{i.name}}---->{{i.desc}}--->{{i.year}}<br>
   {% endfor %}
</body>
</html>  {% endcomment %}



{% comment %} # //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Detail View part2 (link generate){% endcomment %}

{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
   {% for i in movie_list %}
   //<a href="movie/{{i.id}}">{{i.name}}<br>//
   <a href="www.google.com">{{i.name}}<br>
   {% endfor %}
</body>
</html>  {% endcomment %}


{% comment %} # //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Detail View part2 (link generate){% endcomment %}
{% comment %} 
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
   {% for i in movie_list %}
   <a href="{% url 'detail' i.id %}">{{i.name}}<br>
   {% endfor %}
</body>
</html>  {% endcomment %}


{% comment %} # //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Name space in django{% endcomment %}
{% comment %} 
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
   {% for i in movie_list %}
   <a href="{% url 'movieapp:detail' i.id %}">{{i.name}}<br>
   {% endfor %}
</body>
</html>  {% endcomment %}

{% comment %} # //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Load static files{% endcomment %}

{% comment %} {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
   //Navbar//
   <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">
         Online movie store
      </a>
   </nav>
   {% for i in movie_list %}
   <a href="{% url 'movieapp:detail' i.id %}">{{i.name}}<br>
   {% endfor %}
</body>
</html>  {% endcomment %}

{% comment %} # //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Base template {% endcomment %}

{% comment %} {% extends 'base.html' %}
{% block body %}
{% for i in movie_list %}
<img src="{{i.img.url}}"  width="100" height="100">
<a href="{% url 'movieapp:detail' i.id %}">{{i.name}}<br>
{% endfor %}
{% endblock %} {% endcomment %}